(defpackage :mini-gp
  (:use :common-lisp)
  (:export launch-gp
	   gp-multiple-runs
	   *generate-constant*
	   gp-constant
	   gp-plus
	   gp-minus
	   gp-times
	   gp-division
	   gp-log
	   gp-square-root
	   gp-power
	   gp-square
	   gp-if
	   gp-and
	   gp-or
	   gp-not
	   gp-<
	   gp-<=
	   gp->
	   gp->=
	   gp-=
	   gp-/=
	   gp-constant-int
	   gp-constant-real
	   gp-true
	   gp-false
	   gp-random-real
	   gp-random-10
	   gp-random-100
	   gp-random-n
	   individual
	   make-individual
	   individual-tree
	   individual-fitness
	   individual-eval-p
	   safe-copy-individual
	   make-random-individual
	   eval-tree
	   compile-tree
	   make-env
	   env-var
	   eval-tree-with-env
	   compile-tree-with-env
	   make-fset
	   build-fset-by-arity
	   build-fset-arity-map
	   function-name
	   function-args
	   ramped-half-and-half
	   full-method-tree-generic
	   grow-method-tree-generic
	   make-population
	   make-gp-params
	   gp-params-total-generations
	   gp-params-pop-size
	   gp-params-initial-depth
	   gp-params-max-depth
	   gp-params-fset
	   gp-params-tset
	   gp-params-fitness
	   gp-params-cx-rate
	   gp-params-mt-rate
	   gp-params-node-rate
	   gp-params-comparator
	   gp-params-elitism
	   gp-params-seed
	   gp-params-generate-constant
	   gp-params-type
	   subtree-mutation
	   ))
  